In [10]:
from network import AudioCRNN
import torch
from network.foundation_model import Network
# from network import AngleProdict
from run import Train
model = Network().to('cuda')
model.load_state_dict(torch.load("./experiment/ckpt/visual/model_epoch_50.pth"))
model.eval()

Network(
  (visual_encoder): VisualEncoder(
    (conv2d_1): Conv2d(3, 128, kernel_size=(32, 32), stride=(32, 32))
  )
  (add_position): PositionalEcoder()
  (visual_transformer_encoder): Encoder(
    (layers): ModuleList(
      (0-2): 3 x EncoderLayer(
        (attention): MultiHeadAttention(
          (attention): ScaleDotProductAttention(
            (softmax): Softmax(dim=-1)
          )
          (w_q): Linear(in_features=128, out_features=128, bias=True)
          (w_k): Linear(in_features=128, out_features=128, bias=True)
          (w_v): Linear(in_features=128, out_features=128, bias=True)
          (w_concat): Linear(in_features=128, out_features=128, bias=True)
        )
        (norm1): LayerNorm()
        (dropout1): Dropout(p=0.2, inplace=False)
        (ffn): PositionwiseFeedForward(
          (linear1): Linear(in_features=128, out_features=64, bias=True)
          (linear2): Linear(in_features=64, out_features=128, bias=True)
          (relu): ReLU()
          (dropout): 

In [2]:
import pickle
with open('loader.pkl' , 'rb') as f:
    loader = pickle.load(f)

In [17]:
for batch in loader:
    audio , visual , angle , action  = batch
    audio , visual , action = audio.to('cuda') , visual.to('cuda') , action.to('cuda')
    # sector_label = torch.remainder(angle + 180, 2*180) // 45
    logits = model(audio.float() , visual)
    predict = logits.argmax(dim=1)
    break

In [18]:
(predict == action).sum() / 128

tensor(0.7734, device='cuda:0')

In [19]:
predict

tensor([1, 0, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 3, 3, 1, 1, 1, 1, 1], device='cuda:0')

In [20]:
action

tensor([3, 0, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 3,
        1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 2, 1, 1, 1, 1,
        1, 0, 1, 1, 3, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 2, 1, 3, 2, 0, 1, 1, 1,
        1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
        1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 3, 2, 1, 1, 3, 3, 0, 1, 1, 2,
        2, 3, 1, 1, 1, 3, 1, 1], device='cuda:0')

In [17]:
predict

tensor([0, 6, 4, 4, 4, 3, 6, 3, 4, 5, 4, 4, 5, 5, 0, 6, 3, 4, 4, 3, 4, 4, 2, 4,
        4, 3, 4, 2, 3, 2, 4, 6, 2, 6, 4, 4, 4, 0, 4, 4, 4, 0, 4, 4, 4, 3, 3, 4,
        4, 0, 4, 4, 2, 4, 4, 4, 2, 4, 4, 0, 2, 4, 4, 4, 4, 2, 3, 4, 4, 4, 4, 0,
        4, 4, 3, 4, 4, 0, 0, 4, 4, 4, 4, 6, 4, 4, 5, 3, 6, 4, 0, 4, 0, 3, 0, 3,
        4, 3, 4, 4, 6, 4, 3, 4, 3, 4, 3, 6, 4, 3, 4, 5, 6, 4, 5, 4, 4, 2, 4, 6,
        4, 6, 4, 3, 5, 3, 0, 6])

In [18]:
sector_label

tensor([0., 6., 4., 4., 4., 3., 6., 3., 4., 6., 4., 4., 5., 5., 0., 6., 3., 4.,
        4., 3., 4., 4., 1., 4., 4., 3., 4., 2., 3., 2., 4., 6., 2., 6., 4., 4.,
        4., 0., 4., 4., 4., 0., 4., 4., 4., 2., 4., 4., 4., 0., 4., 4., 2., 3.,
        4., 4., 2., 4., 4., 0., 2., 4., 4., 4., 4., 2., 3., 4., 4., 3., 4., 0.,
        4., 4., 3., 4., 4., 0., 0., 4., 4., 4., 4., 6., 4., 4., 5., 2., 6., 4.,
        0., 4., 0., 3., 0., 3., 4., 3., 4., 4., 6., 4., 3., 4., 3., 4., 3., 6.,
        4., 3., 4., 5., 6., 4., 6., 4., 4., 2., 4., 6., 4., 6., 3., 3., 5., 3.,
        0., 6.])